### ISSUE TITLE
Issue on deploying Caduces Testnet

### ISSUE THREAD

**Issue by amankakar** [Zoltu/deterministic-deployment-proxy#15]
I have changed the ``$JSON_RPC``  to `https://galaxy.block.caduceus.foundation` but whenever I run command `./script/test.sh` to deploy it gives error of 
`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"authentication needed: password or unlock"}}`

**Comment by MicahZoltu** [comment]
It sounds like you aren't allowed to submit transactions via that RPC endpoint.  Ideally, you would run your own blockchain node which you can submit transactions from, or you'll need to find someone else who is running a nod that accepts new transactions.

Ultimately, this is an issue with the JSON-RPC node that you are using and not the script, so I am going to close this issue.  However, if you comment here I will still receive notification and try to help where I can.

**Comment by amankakar** [comment]
Yeah you are right I have reached to same conclusion. will give it a try. thanks
