### ISSUE TITLE
How can we use CREATE2 deployer via hardhat?

### ISSUE THREAD

**Issue by tab00** [Zoltu/deterministic-deployment-proxy#16]
I see that the CREATE2 deployer has already been deployed onto most popular blockchains at 0x7A0D94F55792C434d74a40883C6ed8545E406D12.

Instead of skipping lines 20 and 23 in test.sh as described in [README.md](https://github.com/Zoltu/deterministic-deployment-proxy/blob/master/README.md), how can we use hardhat to deploy a new contract using an existing CREATE2 deployer?

**Comment by tab00** [comment]
I couldn't find any source code or abi of the CREATE2 deployer. Is there a "deploy()" function that we can just call to do a deployment?

**Comment by MicahZoltu** [comment]
To deploy with other tools (besides the script), you would go through the process as normal and just change the `to` address on the transaction from `null` (which is how normal transaction based contract deployment works) to the address of the proxy `0x7A0D94F55792C434d74a40883C6ed8545E406D12`.  This was designed intentionally to make it so you can deploy as close to "normal" as possible.

**Comment by tab00** [comment]
OK thanks, so we just need to add `to: "0x7A0D94F55792C434d74a40883C6ed8545E406D12"` into the `sendTransaction` argument.

It's quite different from other CREATE2 factory contracts that have functions like `deploy` and `deployedAddress` e.g. https://docs.axelar.dev/dev/general-message-passing/solidity-utilities#constant-address-deployer .

How can we get the address of the contract before it's deployed?

**Comment by MicahZoltu** [comment]
The purpose of this is to make it so you can deterministically deploy contracts at a deterministic address across chains from an EOA.  If you already have a deployed contract on multiple chains, you can just use that to do the deployment with `CREATE2` as you suggested.

The deployment proxy returns the address of the created contract as a convenience, so you can just use `eth_call` with the same parameters as you would deploy with to get the destination address:
```json
{
	"jsonrpc":"2.0",
	"id":1,
	"method": "eth_call",
	"params": [
		{
			"to":"0x7A0D94F55792C434d74a40883C6ed8545E406D12",
			"data":"0x$BYTECODE"
		},
		"latest"
	]
}
```
Alternatively, you can calculate it by hand in the language of your choice, here is pseudocode for calculating the address in TypeScript:
```ts
export async function getDeploymentAddress(deploymentBytecode: Uint8Array) {
	const proxyDeployerAddress = toBytes(0x7A0D94F55792C434d74a40883C6ed8545E406D12n, 20)
	const salt = toBytes(0n, 32)
	const deploymentBytecodeHash = toBytes(await keccak256(deploymentBytecode), 32)
	return await keccak256([0xff, ...proxyDeployerAddress, ...salt, ...deploymentBytecodeHash]) & 0xffffffffffffffffffffffffffffffffffffffffn
}
```
