### ISSUE TITLE
CREATE3 version

### ISSUE THREAD

**Issue by tab00** [Zoltu/deterministic-deployment-proxy#17]
Can we have a version for CREATE3?

With CREATE3, the resulting address of a deployed contract is no longer dependent on contract bytecode.

**Comment by MicahZoltu** [comment]
I don't believe there is such a thing as a `CREATE3` opcode like there is for `CREATE` or `CREATE2`.  If you are referring to the pattern of deploying via a proxy contract as described at https://github.com/transmissions11/solmate/blob/main/src/utils/CREATE3.sol, then that is solving a separate problem from this and is unrelated.

You are certainly welcome to use something like that if that is what you are looking for!  There are also people who have published factories for making deployment via that technique easier like https://github.com/ZeframLou/create3-factory/blob/main/src/CREATE3Factory.sol.
