### ISSUE TITLE
deploy entrypoint contract to a new L2 chain

### ISSUE THREAD

**Issue by aymentrosh** [Zoltu/deterministic-deployment-proxy#19]
how can I get the [entrypoint](https://github.com/0xFableOrg/account-abstraction/blob/version0.6.0/contracts/core/EntryPoint.sol) contract deployed to a new L2 op stack chain using this [repository](https://github.com/Arachnid/deterministic-deployment-proxy)
we have the RPC URL of our testnet and we don't want to enable the `pre-eip-155` txs for security reasons so we want to deploy it deterministically

**Comment by MicahZoltu** [comment]
The options available:
1. Enable pre-eip-155 transactions.  This only is necessary for this one transaction.
2. Somehow manually get the transaction into a block.  If the chain has some sort of MEV thing or block builder thing this may be possible.
3. Talk to the chain authors and get them to manually deploy the contract in a hard fork.

**Comment by 0xfreeman** [comment]
> this was fixed after enabling pre-eip-155 transactions on op-geth

sorry😊，how to enabling pre-eip-155 transactions on op-geth.

**Comment by 0xfreeman** [comment]
> to enable pre-eip-155 transactions u need to add this flag ` --rpc.allow-unprotected-txs=true` to ur op-geth @0xfreeman

Thanks🎉
