### ISSUE TITLE
Can't be used on Arbitrum and Optimism

### ISSUE THREAD

**Issue by paulrberg** [Zoltu/deterministic-deployment-proxy#7]
My understanding is that the deployer address has been "retrodicted" with Nick's method, and the chosen gas price and the gas limit influence what value the deployer address has.

If that is correct, this deployment proxy cannot be used on optimistic rollup chains like [Arbitrum](arbitrum.io) or [Optimism](https://optimism.io/), because of the way gas is calculated there. E.g. a basic aETH transfer costs ~700k.

**Comment by MicahZoltu** [comment]
The gas limit for the transaction was intentionally chosen to be "significantly higher than necessary" to ensure that moderate changes to gas pricing shouldn't affect the ability to deploy this in the future.  However, very significant gas pricing changes may be too much for the excessive limit to handle.

**Comment by gakonst** [comment]
FYI the contract has been deployed via admin functionality on Arbitrum at the same address

**Comment by paulrberg** [comment]
@gakonst oh, that's so cool. Do you know anyone who has the ability to set the deployment proxy at the same address on Optimism?

**Comment by tynes** [comment]
There are some existing deterministic deployment proxies on Optimism, see https://github.com/ethereum-optimism/optimism/issues/1883

EIP-1820: https://optimistic.etherscan.io/address/0x1820a4b7618bde71dce8cdc73aab6c95905fad24#code
EIP-2470: https://optimistic.etherscan.io/address/0xce0042b868300000d44a59004da54a005ffdcf9f#code

You should be able to deploy this proxy to Optimism as well

**Comment by smartcontracts** [comment]
Should be deployable to Optimism, can use standard deploy flow

**Comment by smartcontracts** [comment]
For future reference, "nicks method" deployments will always work on Optimism, sometimes just need to give the account a little extra ETH to pay for fees

**Comment by paulrberg** [comment]
Thanks @smartcontracts for deploying Micah's deployment proxy on Optimism!

> For future reference, "nicks method" deployments will always work on Optimism, sometimes just need to give the account a little extra ETH to pay for fees

Gotcha.
