### ISSUE TITLE
Wich variables to change in order to deploy the example contract with my unlocked account?

### ISSUE THREAD

**Issue by yieniggu** [Zoltu/deterministic-deployment-proxy#8]
Hey, i'd like to test the feature, however the contract seems to be deployed to every possible chain with the test script parameter. How could i run the script using my own account details?

Thanks for any help!

**Comment by MicahZoltu** [comment]
Easiest way would be to spin up a new in-memory chain.  Nethermind and Geth (and probably Besu and Erigon) have a mode that lets you boot up with a temporary in-memory chain.  I think Geth calls it a dev chain, Nethermind calls it `spaceneth`.  You would just run your client like this with JSON-RPC enabled and use one of the accounts with huge amounts of ETH to run the script.

**Comment by MicahZoltu** [comment]
Closing this issue as Q&A which was answered.
